"""add_bus_crowding_logs

Revision ID: 1c6938e66d31
Revises: 0007_map_markers
Create Date: 2026-04-20 19:48:09.526790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1c6938e66d31'
down_revision: Union[str, None] = '0007_map_markers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_crowding_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('plate_no', sa.String(length=20), nullable=False),
    sa.Column('crowded', sa.Integer(), nullable=False),
    sa.Column('arrive_in_seconds', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['bus_stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crowding_route_stop_at', 'bus_crowding_logs', ['route_id', 'stop_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_crowding_route_stop_at', table_name='bus_crowding_logs')
    op.drop_table('bus_crowding_logs')
    # ### end Alembic commands ###
